### PR TITLE
Adds 2 implementations: component vs decorator

### PR DESCRIPTION
**Pull request by joaomilho**
Now you tell me which one is the best.

### CODE REVIEW

**Comment by pirelenito** [comment]
We have toyed with the idea of "decorators" in the past for the entanglement API and gave-up on it given the extra setup step doesn't add much value.

I would go for the plain component. What do you think @xaviervia ?

**Comment by joaomilho** [comment]
The "extra setup" allows the rendered component to be a real component and not a list of props passed under a "props" key. See the difference:

``` html
const DecoratedDialog = scatterOrRender(Dialog)
    <DecoratedDialog
      adapter={undefined}
      items={['one', 'two', 'three']}
      onClick={(value, number) => window.alert('clicked' + value + number)}
    />

// vs

    <ScatterOrRender
      adapter={undefined}
      component={Dialog}
      name='Dialog'
      props={{
        onClick: (value, number) => window.alert('clicked' + value + number),
        items: ['one', 'two', 'three']
      }}
    />
```

Notice that the 2nd also needs to be wrapped in a component anyway.

**Comment by xaviervia** [comment]
That was the original approach, but we noticed two main shortcomings:
1. There is a hard to solve naming conflict with the `adapter` prop. It has to be either:
   - Namespaced (something like `reactEntanglementAdapter`)
   - Passed to the HOC (original approach, very problematic since most adapters are instances)
   - Put in the `React.context` (this needs to be just a sugar, `React.context` is neither stable nor recommended)
2. It makes the API less straightforward. This is a more debatable point IMO since we could also provide a non-component scatterer (`scatter('Dialog', { onClick: () => {}, items: [] })`) to be used directly in a subscriber or any similar approach.

I think we have an use-case clarity problem with React Entanglement, in the sense that sometimes it seems we want to do a solution for local/remote rendering of a particular component (which was the original intention) and sometimes we just want to have a generic solution for remote rendering (which was the idea behind the current API). An idea I'm toying with right now is to create another package called `entanglement-scatter` that contains the plain function approach and has no dependency whatsoever on React, which can then be used in a service worker, in a server, etc.

**Comment by joaomilho** [comment]
What is the problem of `scatterOrRender(Dialog, adapter)`? Isn't the adapter ready by this point in time?

**Comment by xaviervia** [comment]
We just have a short discussion with @joaomilho and we think that we should split the API according to use cases, and have only two, very clear and separated APIs for the scattering.

## 1st case: render local or remotely

**Rationale**: if we are unsure if the element is going to be rendered local or remotely, it makes sense to use React components. In this case, the element might also be embedded in a rendering tree, which makes it more natural if we use "real looking" components. We want to just use "Dialog" and not care that it is actually scattered: whether it will be rendered remotely or not is up to the `Entanglement`.

``` javascript
const Dialog = Entanglement.scatterOrRender(OriginalDialog)

render(
  <Entanglement adapter={isRemote ? adapter : undefined}>
    <div>
      <Dialog
        title='Dialog title'
      />
    </div>
  </Entanglement>
)
```

As you can see, there is nothing odd with the Dialog for the consumer. Also, the `adapter` prop is not hijacked, so any component should work fine scattered.

## 2nd case: always remote should be just a function

**Rationale**: if we know that we are going to render remotely all the time, there is no point in including the scatter as part of any rendering tree. React Entanglement (or some other lib) should provide a very simple function wrapper that allows to call the `render`, `unmount` and `onHandle` methods directly.

``` javascript
// Not the Entanglement.scatter function. This is just a function that wraps the adapter
scatter('Dialog', adapter).render({ title: 'Dialog title' })
```

Of course this would need some sort of binding to the state (in case of Redux, with a subscriber) but that's a separate issue.

**Comment by joaomilho** [comment]
Ok, so the problem of the 1st example is this:

"Dialog" depends on data in the store. Therefore, if we look at it's implementation, we'll see something like:

``` js
// Dialog.jsx
const Dialog = (props) => {
   //... render something with props
}

export default connect(mapStateToProps, mapDispatchToProps)(Dialog)
```

Now, going back to the example, this Dialog component would be captured by:

``` js
// Main.jsx
import OriginalDialog from './Dialog.jsx'

const Dialog = Entanglement.scatterOrRender(OriginalDialog)
```

So I assume `scatterOrRender` will have the following signature: `(Component) => (props, context) =>` so it gets the context's adapter and decides to render inline or scatter. Rendering inline is fine, since all it has to do is `<Component {...props} />`, but if has to scatter the component it needs to extract the props from the component (to pass to the scatter function or component). I will not even consider the possibility of doing a shallow render and getting them, cause it is an evil subversion of the intended usage of React.

Therefore I conclude that there _must_ be something in between that simply is a function mapping `store => props`. This means that the signature of `scatterOrRender` will actually be closer to the `scatter`, something like:

``` js
const Dialog = Entanglement.scatterOrRender(OriginalDialog, mappingFunction, store)
```

Please LMK what is the flaw in my reasoning, if there is any.

**Comment by joaomilho** [comment]
Actually @pirelenito commented that it's ok to get the props from a child. So I may try this approach then.

**Comment by xaviervia** [comment]
@joaomilho in the example you take the assumption that this is going to be a connected container, from `react-redux`. This library aims to have no relationship with Redux at all. That's why I don't see the need for mapping function _in this library_.

Now, if we were to implement a connected container for `react-redux` that _only renders a scattered component_, your reasoning makes perfect sense (instead of building the container manually, make a function that builds it. I think thought that such scatterer should be a different library, since it is a particular use case. If the scattered component is rendered anywhere else in the rendering tree (or if the app doesn't use `react-redux`) the mapping is not needed.

**Comment by xaviervia** [comment]
To recap: I think that you're describing _yet another API_. It's not a replacement for the first case (which is rendering anywhere on the three, agnostic of store solution) or the second case (which is a very low level wrapper for the adapter, framework agnostic), it's a third one, aimed at the particular scenario of using the entanglement to render locally or remotely at the root level in a React-Redux container.

We should probably implement all of them. The good thing is that they are not conflicting at all, as long as the adapter interface is kept the same anything goes.

**Pull request merged**
